//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.10 at 11:42:11 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://gcomputer.net/webservices/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.ing.assessment.dilbert.stubs;
